### ISSUE TITLE
ModuleNotFoundError: No module named 'redis'

### ISSUE THREAD

**Issue by ogoldberg** [continuum-llms/chatgpt-memory#28]
Any thoughts on this error I'm getting? Can't seem to wrap my head around it. I set up a redis cloud environment, copied `.env.example` to  `.env` and updated all the values.

```
>  uvicorn rest_api:app --host localhost --port 8000
Traceback (most recent call last):
  File "/Users/og/Library/Python/3.9/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/Users/og/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/og/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/og/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/og/Library/Python/3.9/lib/python/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/og/Library/Python/3.9/lib/python/site-packages/uvicorn/main.py", line 403, in main
    run(
  File "/Users/og/Library/Python/3.9/lib/python/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/Users/og/Library/Python/3.9/lib/python/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/og/Library/Python/3.9/lib/python/site-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/Users/og/Library/Python/3.9/lib/python/site-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/og/Library/Python/3.9/lib/python/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/Users/og/Library/Python/3.9/lib/python/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/og/src/ufr/sandbox/chatgpt-memory/rest_api.py", line 6, in <module>
    from chatgpt_memory.datastore import RedisDataStore, RedisDataStoreConfig
  File "/Users/og/src/ufr/sandbox/chatgpt-memory/chatgpt_memory/datastore/__init__.py", line 2, in <module>
    from chatgpt_memory.datastore.redis import RedisDataStore  # noqa: F401
  File "/Users/og/src/ufr/sandbox/chatgpt-memory/chatgpt_memory/datastore/redis.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
```

**Comment by ogoldberg** [comment]
Is this a directory issue?

**Comment by shahrukhx01** [comment]
@ogoldberg you're missing the Redis package. Running ‘poetry install’ should resolve this

**Comment by ogoldberg** [comment]
Thanks!
I've actually run poetry install many times. I think maybe I'm having an issue with python versioning/virtual environments.

**Comment by shahrukhx01** [comment]
You could try directly installing using ‘pip’

**Comment by ogoldberg** [comment]
I did that before and now it says "Requirement already satisfied"

**Comment by shahrukhx01** [comment]
You can try the following versions of each dependency 

python = "^3.10"
pydantic = "^1.10.0"
pytest = "^7.2.2"
numpy = "^1.24.2"
tqdm = "^4.65.0"
requests = "^2.28.2"
transformers = "^4.26.1"
redis = "^4.5.1"
openai = "^0.27.2"
langchain = "^0.0.113"
python-dotenv = "^1.0.0"
streamlit = "^1.21.0"
fastapi = "^0.95.1"
uvicorn = "^0.21.1"

**Comment by ogoldberg** [comment]
that's an exact match to what's in the `pyproject.toml` file. 
Are you recommending to pip install each of those to see if that resolves it?

**Comment by shahrukhx01** [comment]
Yes, alternatively that may very well work. Also, pinging @nps1ngh could you also pls suggest any other alternative?

**Comment by nps1ngh** [comment]
Hi, 

thanks for the interest in the project @ogoldberg (and thanks for the ping @shahrukhx01).

I think this might be related to https://github.com/continuum-llms/chatgpt-memory/issues/21#issuecomment-1484187440.

@ogoldberg, could you please try running the command with `poetry run` in front of it?
So 

```bash
poetry run uvicorn rest_api:app --host localhost --port 8000
```

**Comment by ogoldberg** [comment]
Thanks, @nps1ngh ! That did it! Much appreciated! I think we should maybe consider updating the docs?
